import itertools

EXERCISE_DB = [
    {"id": 1, "activity": "Weight Training", "intensity": "Light", "met": 3.0, "time": 20},
    {"id": 2, "activity": "Weight Training", "intensity": "Light", "met": 3.0, "time": 30},
    {"id": 3, "activity": "Weight Training", "intensity": "Light", "met": 3.0, "time": 60},
    {"id": 4, "activity": "Weight Training", "intensity": "Moderate", "met": 4.5, "time": 20},
    {"id": 5, "activity": "Weight Training", "intensity": "Moderate", "met": 4.5, "time": 30},
    {"id": 6, "activity": "Weight Training", "intensity": "Moderate", "met": 4.5, "time": 60},
    {"id": 7, "activity": "Weight Training", "intensity": "Heavy", "met": 6.0, "time": 20},
    {"id": 8, "activity": "Weight Training", "intensity": "Heavy", "met": 6.0, "time": 30},
    {"id": 9, "activity": "Weight Training", "intensity": "Heavy", "met": 6.0, "time": 60},
    {"id": 10, "activity": "Walking", "intensity": "Slow", "met": 2.5, "time": 20},
    {"id": 11, "activity": "Walking", "intensity": "Slow", "met": 2.5, "time": 30},
    {"id": 12, "activity": "Walking", "intensity": "Slow", "met": 2.5, "time": 40},
    {"id": 13, "activity": "Walking", "intensity": "Slow", "met": 2.5, "time": 60},
    {"id": 14, "activity": "Walking", "intensity": "Moderate", "met": 4.0, "time": 20},
    {"id": 15, "activity": "Walking", "intensity": "Moderate", "met": 4.0, "time": 30},
    {"id": 16, "activity": "Walking", "intensity": "Moderate", "met": 4.0, "time": 40},
    {"id": 17, "activity": "Walking", "intensity": "Moderate", "met": 4.0, "time": 60},
    {"id": 18, "activity": "Run", "intensity": "Slow", "met": 8.0, "time": 15},
    {"id": 19, "activity": "Run", "intensity": "Slow", "met": 8.0, "time": 30},
    {"id": 20, "activity": "Run", "intensity": "Slow", "met": 8.0, "time": 45},
    {"id": 21, "activity": "Run", "intensity": "Moderate", "met": 10.0, "time": 15},
    {"id": 22, "activity": "Run", "intensity": "Moderate", "met": 10.0, "time": 30},
    {"id": 23, "activity": "Run", "intensity": "Moderate", "met": 10.0, "time": 45},
    {"id": 24, "activity": "Run", "intensity": "Fast", "met": 12.5, "time": 15},
    {"id": 25, "activity": "Run", "intensity": "Fast", "met": 12.5, "time": 30},
]